### ISSUE TITLE
Base64.isValidBase64 cannot process chunked input

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#100]
The regex use doesn't take into account newlines, as is common in certificates, e.g. 

> TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZW
> xpdCwgc2VkIGRvIGVpdXNtb2QgdGVtcG9yIGluY2lkaWR1bnQgdXQgbGFib3JlIGV0IGRvb
> G9yZSBtYWduYSBhbGlxdWEuIFV0IGVuaW0gYWQgbWluaW0gdmVuaWFtLCBxdWlzIG5
> vc3RydWQgZXhlcmNpdGF0aW9uIHVsbGFtY28gbGFib3JpcyBuaXNpIHV0IGFsaXF1aXAg
> ZXggZWEgY29tbW9kbyBjb25zZXF1YXQuIER1aXMgYXV0ZSBpcnVyZSBkb2xvciBpbiByZ
> XByZWhlbmRlcml0IGluIHZvbHVwdGF0ZSB2ZWxpdCBlc3NlIGNpbGx1bSBkb2xvcmUgZX
> UgZnVnaWF0IG51bGxhIHBhcmlhdHVyLiBFeGNlcHRldXIgc2ludCBvY2NhZWNhdCBjdXBp
> ZGF0YXQgbm9uIHByb2lkZW50LCBzdW50IGluIGN1bHBhIHF1aSBvZmZpY2lhIGRlc2Vyd
> W50IG1vbGxpdCBhbmltIGlkIGVzdCBsYWJvcnVtLg==

In the case of Jaxb, the underlying implementation can support newlines just fine. Instead of introducing an uncompiled Regex to ever call, just let the underlying implementation take care of validating. I think the isValidBase64 call should be removed from the decode method.

**Comment by wmiaw** [comment]
Unfortunately, DatatypeConverter doesn't return or throw an error on invalid Base64. And I need a contract on this function—I picked the contract we used to have with the original Netflix Base64 and the one that is currently being followed by the JavaScript Base64 library.

I will look into supporting newlines in both the Java and JavaScript versions and at compiling the regex.

**Comment by quidryan** [comment]
OMG, DatatypeConverter not returning or throwing an exception is downright criminal.

**Comment by quidryan** [comment]
I don't think that's the only problem. I'm also see some tests fail for a shorter string: 

    Caused by: java.lang.IllegalArgumentException: Invalid Base64 encoded string: TmbpuKnOtFIx_cJNHW99dw==
        at com.netflix.msl.util.Base64ImplJava8.decode(Base64ImplJava8.java:23)
        at com.netflix.msl.util.Base64.decode(Base64.java:97)
        at com.netflix.msl.crypto.MslCiphertextEnvelope.<init>(MslCiphertextEnvelope.java:202)
        ... 27 more

I think the regex is missing _, which is in the encode map for DatatypeConverterImpl. This is pointing out that if we use different base64 encoding maps, we could be in real trouble. Specifically character 62 and 63 (https://en.wikipedia.org/wiki/Base64). Since we used DatatypeConverterImpl, we have to stick with it's encoding style. I have to check that Java 8's Base64 and Android's encoding match, I doubt they do.

We might also to enforce this by doing a isValidBase64 on the output of an encode.

**Comment by wmiaw** [comment]
I don't see '_' in the default encode map for DatatypeConverterImpl.

    private static char[] initEncodeMap() {
        char[] map = new char[64];
        int i;
        for (i = 0; i < 26; i++) {
            map[i] = (char) ('A' + i);
        }
        for (i = 26; i < 52; i++) {
            map[i] = (char) ('a' + (i - 26));
        }
        for (i = 52; i < 62; i++) {
            map[i] = (char) ('0' + (i - 52));
        }
        map[62] = '+';
        map[63] = '/';

        return map;
    }

The '_' character is only for URL-safe Base64. Those should be going through `JsonUtils`. Where did your example encoded string come from? It couldn't be from the `MslCiphertextEnvelope.toJSONString()` because that doesn't use URL-safe Base64.

**Comment by quidryan** [comment]
MslCiphertextEnvelope::toJSONString is encoding the IV and it includes the '_'

**Comment by quidryan** [comment]
I think I found the problem on our side, a Java8 URL encoder was incorrectly being used.
