### ISSUE TITLE
msl-cli is now published as a war, not a jar

### ISSUE THREAD

**Issue by dreynaud** [Netflix/msl#136]
Looks like this is because of this commit: https://github.com/Netflix/msl/commit/f9cb4afc4a79630613839028e13198a44a821ad8

It was a jar in this version:
https://bintray.com/netflixoss/maven/msl/1.1199.0#files/com/netflix/msl/msl-cli/1.1199.0

But a war here:
https://bintray.com/netflixoss/maven/msl/1.1204.0#files/com/netflix/msl/msl-cli/1.1204.0

**Comment by dreynaud** [comment]
I think just adding `jar.enabled = true` to mslcli/build.gradle would fix it

**Comment by aliddeke** [comment]
Do you know of anyway to test this out?

**Comment by dreynaud** [comment]
Fixed in v1.1206.0
