### ISSUE TITLE
Possible NPE in concurrent use of MessageOutputStream

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#238]
https://github.com/Netflix/msl/blob/bfeff44346e2188c7ba234a578dbdfbffc6c4ab6/core/src/main/java/com/netflix/msl/msg/MessageOutputStream.java#L278

If MessageOutputStream::close is called while MessageOutputStream::flush() was running, currentPayload.toByteArray() could NPE, since MessageOutputStream::close sets currentPayload to null.

If MessageOutputStream isn't meant to be thread-safe, then the null check in that line is redundant because line 264 already ensured that the variable is not null.

**Comment by wmiaw** [comment]
MessageOutputStream is not supposed to be thread-safe. All of the classes that are thread-safe or interfaces that need their concrete implementations to be thread-safe should be documented as such in the Javadoc describing the class.

Looks like I need to double-check the null check you are referencing.

**Comment by quidryan** [comment]
In that case, the null check is just not needed, it's not causing any harm though.
