### ISSUE TITLE
Expose isEncrypted() and isIntegrityProtected() functions on MessageInputStream

### ISSUE THREAD

**Issue by wmiaw** [Netflix/msl#279]
More convenient functions on `MessageInputStream` to tell you if the application data is encrypted and integrity protected are useful for an application that wants to confirm the properties of any received message. (This functionality may be exposed through some other less convenient method—we should double-check for that before moving forward to ensure there isn't more than one way for an application to find this out.)

**Comment by padolph** [comment]
placeholder comment
