### ISSUE TITLE
Different devices can login to same account profile and use simultaneously. Add device registration capability.

### ISSUE THREAD

**Issue by pritamneog29** [Netflix/msl#292]
Please tighten authentication as many people can use same profile simultaneously which leads to account sharing. The only constraint currently present is you can't watch same show simultaneously afaik.

**Comment by wmiaw** [comment]
Using the same user credentials from more than one device (MSL entity) is something that would need to be addressed in business logic above the MSL protocol layer. You may be interested in the [Netflix Terms of Use](https://help.netflix.com/legal/termsofuse) or searching the [Help Center](https://help.netflix.com/en).

If you believe there is a flaw or weakness in the Netflix service user authentication, please reach out to me directly at wmiaw@netflix.com.
