### ISSUE TITLE
MslException setUser/setEntity do not retain original Exception type

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#58]
If I have a MslUserAuthException and then I call .setUser(userIdToken), it becomes a MslException, which then requires a broader method signature than is needed. Is it possible to add a generic type to MslException so that the child exception type can be kept?

**Comment by wmiaw** [comment]
Similar to the other MslException subclasses, to do this the subclasses override the set*() functions. However, you shouldn't be throwing a MslUserAuthException with a user ID token, only attaching user authentication data. Why do you want to call MslUserAuthException.setUser(userIdToken)?
