### ISSUE TITLE
Move Wiki to Markdown in the repository

### ISSUE THREAD

**Issue by quidryan** [Netflix/msl#87]
By having the documentation in the repository directly, it can be updated/committed/submitted at the same the feature/change is made. Github allows editing files in the repository directly, which means we keep the ability to update the docs via the website, just like in the wiki. 

It also opens the possibility to somehow syncing the docs with the code some day.

**Comment by wmiaw** [comment]
I also think it would be nice to have documentation and code changes match within a commit, however I do think it's worth keeping the documentation in sync with the way GitHub does things. That's also why the gh-pages branch does exist. So I want to keep the Wiki tab. I don't think the additional overhead is that bad considering the very low frequency of necessary changes to the documentation.
